services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    depends_on:
      influxdb:
        condition: service_started
      mosquitto:
        condition: service_started

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    volumes:
      - "./influxdb:/var/lib/influxdb:rw"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - "./grafana:/var/lib/grafana:rw"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto:/mosquitto"
