[agent]
    flush_interval = "10s"
    interval = "10s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.mem]]

[[inputs.mqtt_consumer]]
    servers=["tcp://mosquitto:1883"]
    topics=["pc/temp"]
    data_format="json"

[[outputs.influxdb]]
  database = "sensorsdata"
  urls = [ "http://influxdb:8086" ]
  username = "telegraf"
  password = "uforobot"